### ISSUE TITLE
Only show errors for same file

### ISSUE THREAD

**Issue by WebFreak001** [Pure-D/atom-ide-d#16]
atom-linter really messes up if giving errors to other files

**Comment by Vild** [comment]
e2ab770b2ab0e2a0c392ae84191d1c5ffbc02876 Fixed this maybe

**Comment by WebFreak001** [comment]
Oh seems like not quite fixed

**Comment by aminya** [comment]
As long as serve-d follows LSP, the linter errors are handled by Atom. I think this is fixed.
