### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by WebFreak001** [Pure-D/atom-ide-d#21]
We should include:
- Coolest features
- Dependencies (dub, dlinter, dcd)
- How to build the debug version

**Comment by Hackerpilot** [comment]
Yes. I would really like a more complete README. I tried setting up atomize-d for a co-worker yesterday and wasn't able to get autocomplete working. I ended up setting him up with Textadept instead.

**Comment by WebFreak001** [comment]
This project needs a rewrite to use Microsoft LSP first. See https://forum.dlang.org/thread/lrbkahaaoimrxdmdzwee@forum.dlang.org

**Comment by aminya** [comment]
I rewrote the readme in #37
