### ISSUE TITLE
spawning dcd-client fails

### ISSUE THREAD

**Issue by andreiamatuni** [Pure-D/atom-ide-d#27]
Uncaught Error: spawn dcd-client ENOENT (events.js:141)

**Comment by andreiamatuni** [comment]
looks like a permission issue. starting atom from the command line with sudo solves the problem.

**Comment by WebFreak001** [comment]
is dcd-client in path? Try typing `dcd-client` and if it works then the plugin should also work

**Comment by andreiamatuni** [comment]
yeah it's in the path, but in /usr/local/bin, which OS X has decided is too dangerous to touch in El Capitan. Also, the completions for imports aren't working for some reason

**Comment by Vild** [comment]
This will be fixed in #28.
Currenty VisualStudio Code with [code-d](https://github.com/Pure-D/code-d) works best for D development.

**Comment by andreiamatuni** [comment]
cool

**Comment by aminya** [comment]
Closing in favor of #42
