### ISSUE TITLE
Register atom-ide-d

### ISSUE THREAD

**Issue by nikibobi** [Pure-D/atom-ide-d#29]
Is this package published? Because I can't find it in the Atom's site nor install it with
`apm install atomize-d`

**Comment by Vild** [comment]
It's not published yet.
It's still not in a state where I want to publish it.
Will publish it when workspace-d support is added

**Comment by nikibobi** [comment]
Oh ok thanks for the quick reply. I guess I'll have to install it manually

**Comment by rogue780** [comment]
@nikibobi how do you install it manually? apm link gives me the error "'workspace-d' is not a valid executable. Please check your user settings and make sure workspace-d is installed!"

**Comment by aminya** [comment]
@WebFreak001 Could you rename the repository to `ide-d` as we already discussed? This is the convention for Atom packages.

**Comment by WebFreak001** [comment]
@aminya does the GitHub name need to be that exact name? I want it to be obvious that it's an atom package, so would atom-ide-d be ok?

**Comment by aminya** [comment]
No, the repo name can be different. `atom-ide-d` works!

**Comment by aminya** [comment]
@WebFreak001 Could you also make the `main` branch the default branch?

**Comment by WebFreak001** [comment]
done

**Comment by aminya** [comment]
Blocked by #39 and #38

**Comment by aminya** [comment]
@WebFreak001 Could you relase a new version of serve-d (beta works too), so I can release this Atom package.

**Comment by WebFreak001** [comment]
beta pre-release is done (0.7.0-beta.5)

**Comment by aminya** [comment]
Thanks. I have not registered the package yet. You can follow the issue here: 
https://github.com/git-lfs/git-lfs/issues/1322#issuecomment-786176373

**Comment by aminya** [comment]
@WebFreak001 Could you enable the setting mentioned in this comment:
https://github.com/git-lfs/git-lfs/issues/1322#issuecomment-786199434

**Comment by WebFreak001** [comment]
done

**Comment by aminya** [comment]
The package is registered now!
